import RegisterForm from "@/components/RegisterForm";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
};
const Register = async () => {
  const session = await getServerSession(authOptions);
  if (session) redirect("/");

  return (
    <div className=" min-h-screen flex justify-center items-center">
      <RegisterForm />
    </div>
  );
};

export default Register;
