import LoginForm from "@/components/LoginForm"
import { getServerSession } from "next-auth"
import {redirect} from "next/navigation"
import { authOptions } from "../api/auth/[...nextauth]/route"

export const metadata = {
  title: "Log in ",
  description: 'Generated by create next app',
}
const Login = async() => {

  const session =await getServerSession(authOptions);
  if(session) redirect('/')

  return (
    <div className=" min-h-screen flex justify-center items-center">
      <LoginForm/>
    </div>
  )
}

export default Login
